const products = [
    {
        _id: '1',
        name: 'Airpod Wireless',
        image: '/images/Moscow.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '2',
        name: 'Airpod Wireless',
        image: '/images/Moscow2.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '3',
        name: 'Airpod Wireless',
        image: '/images/Moscow3.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '4',
        name: 'Airpod Wireless',
        image: '/images/Moscow4.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '5',
        name: 'Airpod Wireless',
        image: '/images/Moscow5.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '6',
        name: 'Airpod Wireless',
        image: '/images/Moscow6.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4.5,
        numReviews: 4,
    },
    {
        _id: '7',
        name: 'Airpod Wireless',
        image: '/images/Moscow7.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 3.5,
        numReviews: 4,
    },
    {
        _id: '8',
        name: 'Airpod Wireless',
        image: '/images/Moscow8.jpg',
        description: 'New generation of Airpods',
        brand: 'Apple',
        caregory: 'Electronics',
        price: 89.99,
        countInStock: 3,
        rating: 4,
        numReviews: 4,
    },
]
export default products